# Generated by Django 6.0.4 on 2026-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='accounts.adminprofile'),
        ),
    ]
