# Generated by Django 6.0.4 on 2026-04-20 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_dealerprofile_subdealerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('dealer', 'Dealer'), ('sub_dealer', 'Sub Dealer'), ('promotor', 'Promotor'), ('customer', 'Customer')], default='dealer', max_length=20),
        ),
        migrations.CreateModel(
            name='PromotorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(blank=True, max_length=5)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('door_no', models.CharField(blank=True, max_length=25, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('town_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('employee', 'Employee'), ('business', 'Business'), ('others', 'Others')], max_length=20, null=True)),
                ('occupation_detail', models.CharField(blank=True, max_length=25, null=True)),
                ('annual_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('promotor_name', models.CharField(blank=True, max_length=50)),
                ('promotor_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('promotor_contact_no', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_sub_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_promotors', to='accounts.subdealerprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(blank=True, max_length=5)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('door_no', models.CharField(blank=True, max_length=25, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('town_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('employee', 'Employee'), ('business', 'Business'), ('others', 'Others')], max_length=20, null=True)),
                ('occupation_detail', models.CharField(blank=True, max_length=25, null=True)),
                ('annual_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_promotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='accounts.promotorprofile')),
            ],
        ),
    ]
