# Generated by Django 6.0.4 on 2026-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role_promotorprofile_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='initial',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_contact_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
