# Generated by Django 6.0.4 on 2026-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_adminprofile_name_adminprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='initial',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
