# Generated by Django 6.0.4 on 2026-04-28 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.announcement')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'replied_by')},
            },
        ),
    ]
