# Generated by Django 6.0.4 on 2026-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_announcementreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='married_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=10),
        ),
    ]
