# Generated by Django 6.0.4 on 2026-04-29 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customerprofile_anniversary_date_customerprofile_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('married_status', models.CharField(blank=True, max_length=10)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('door_no', models.CharField(blank=True, max_length=25)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('town_name', models.CharField(blank=True, max_length=100)),
                ('city_name', models.CharField(blank=True, max_length=25)),
                ('district', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12)),
                ('pan_no', models.CharField(blank=True, max_length=25)),
                ('occupation', models.CharField(blank=True, max_length=20)),
                ('occupation_detail', models.CharField(blank=True, max_length=25)),
                ('annual_salary', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField(blank=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='profile_update_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
