# Generated by Django 6.0.4 on 2026-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
