# Generated by Django 4.2.11 on 2026-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_homebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jewelryproduct',
            old_name='weight_grams',
            new_name='cross_weight',
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='making_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='stone_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
    ]
