# Generated by Django 4.2.11 on 2026-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
