# Generated by Django 4.2.11 on 2026-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_metalrate_diamond_18k_metalrate_diamond_22k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryproduct',
            name='grade',
            field=models.CharField(blank=True, choices=[('22k', '22K'), ('24k', '24K'), ('999', '999'), ('18k', '18K'), ('92', '92'), ('', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='metal',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('platinum', 'Platinum')], max_length=10),
        ),
    ]
